<!-- BEGIN (write your solution here) -->
<table>
    <?php foreach ($posts as $post): ?>
        <tr>
            <td>
                <?= $post['id'] ?>
            </td>
            <td>
                <a href="/posts/<?= $post['id'] ?>"><?= $post['name'] ?></a>
            </td>
        </tr>
    <?php endforeach ?>
</table>
<table>
    <tr>
        <td>
            <?php if($page > 1): ?>
                <a href="/posts?page=<?= $page - 1 ?>">Туда</a>
            <?php endif; ?>
        </td>
        <td><a href="/posts?page=<?= $page + 1 ?>">Сюда</a></td>
    </tr>
</table>
<!-- END -->
