<?php if (count($flash) > 0): ?>
    <ul>
        <?php foreach ($flash as $messages): ?>
            <?php foreach ($messages as $message): ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<!-- BEGIN (write your solution here) -->
<?php if (isset($_SESSION['user'])): ?>
    <div>
        <b><?= $_SESSION['user']['name']?></b>
    </div>
    <form action="/session" method="post">
        <input type="hidden" name="_METHOD" value="DELETE">
        <button type="submit">Sign Out</button>
    </form>
<?php else: ?>
<form action="/session" method="post">
    <label><b>Username</b>
    <input type="text" name="user[name]" value="<?= $user['name'] ?? 'Enter Username' ?>" placeholder="Enter Username">
    </label>
    <label><b>Password</b>
    <input type="password" name="user[password]" value="<?= $user['name'] ?? 'Enter Username' ?>" placeholder="Enter Password">
    </label>
    <button type="submit">Sign In</button>
</form>
<?php endif ?>
<!-- END -->
